version: '4.10.1'

services:
  web:
    # Берем Dockerfile из каталога app
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    # Запускаем сервер gunicorn
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    # Открываем порт 8000 внутри и снаружи
    expose:
      - 8000
    env_file:
      - ./.env.prod
    # Дожидаемся запуска контейнера db
    depends_on:
      - db

  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:15.2-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
      
volumes:
  postgres_volume: